[pg]
description = "PostgreSQL 15 Server (Streaming with Retention)"
conninfo = host=pg user=barman dbname=postgres password=barman
streaming_conninfo = host=pg user=barman dbname=postgres password=barman
backup_method = postgres
streaming_archiver = on
slot_name = barman
retention_policy = REDUNDANCY 2
