[pg]
description = "PostgreSQL 15 Server (Streaming)"
conninfo = host=pg user=barman dbname=postgres password=barman
streaming_conninfo = host=pg user=barman dbname=postgres password=barman
backup_method = postgres
streaming_archiver = on
slot_name = barman

