{
 "title": "PostgreSQL Performance Dashboard",
 "tags": [
  "postgres",
  "database"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "PostgreSQL Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Postgres Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "Total Cluster Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pg_database_size_bytes)" }
   ]
  },
  {
   "title": "Active Backends/Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)"
    }
   ]
  },
  { "title": "Transaction Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Transaction Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[1m]))",
     "legendFormat": "Commits / sec"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback[1m]))",
     "legendFormat": "Rollbacks / sec"
    }
   ]
  }
 ]
}